-- MySQL Script generated by MySQL Workbench
-- Fri 23 Jan 2026 03:25:12 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wiki
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wiki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wiki` ;
USE `wiki` ;

-- -----------------------------------------------------
-- Table `wiki`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wiki`.`items` (
  `qid` VARCHAR(20) NOT NULL,
  `label` VARCHAR(30) NOT NULL,
  `description` VARCHAR(255) NULL,
  `label_ru` VARCHAR(30) NULL,
  `description_ru` VARCHAR(255) NULL,
  PRIMARY KEY (`qid`),
  UNIQUE INDEX `qid_UNIQUE` (`qid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wiki`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wiki`.`properties` (
  `pid` VARCHAR(7) NOT NULL,
  `plabel` VARCHAR(45) NOT NULL,
  `pdescription` VARCHAR(255) NULL,
  PRIMARY KEY (`pid`),
  UNIQUE INDEX `pid_UNIQUE` (`pid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wiki`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wiki`.`events` (
  `eid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qid` VARCHAR(20) NOT NULL COMMENT 'Link to Items table. Format Qxxxxxxxxx - internal WiKi ID',
  `property` VARCHAR(7) NOT NULL COMMENT 'Property ID. Define type of event.',
  `year` SMALLINT NOT NULL COMMENT 'Year of the event. Can be as positive as nagative.',
  `month` TINYINT UNSIGNED NOT NULL,
  `day` TINYINT UNSIGNED NOT NULL,
  `date` VARCHAR(11) NOT NULL COMMENT 'BC attribute (1 for BC, 0/null for AD)',
  INDEX `fk_events_qid_idx` (`qid` ASC) VISIBLE,
  INDEX `fk_property_pid_idx` (`property` ASC) VISIBLE,
  INDEX `year_idx` (`year` ASC) VISIBLE,
  INDEX `month_idx` (`month` ASC) VISIBLE,
  INDEX `day_idx` (`day` ASC) VISIBLE,
  PRIMARY KEY (`eid`),
  UNIQUE INDEX `eid_UNIQUE` (`eid` ASC) VISIBLE,
  CONSTRAINT `fk_events_qid`
    FOREIGN KEY (`qid`)
    REFERENCES `wiki`.`items` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_pid`
    FOREIGN KEY (`property`)
    REFERENCES `wiki`.`properties` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wiki`.`instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wiki`.`instances` (
  `iid` VARCHAR(20) NOT NULL COMMENT 'IID = QID',
  `label` VARCHAR(30) NOT NULL,
  `description` VARCHAR(255) NULL,
  `label_ru` VARCHAR(30) NULL,
  `description_ru` VARCHAR(255) NULL,
  PRIMARY KEY (`iid`),
  UNIQUE INDEX `qid_UNIQUE` (`iid` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Dictionalry of interesting types of instances (values for property P31)\nThe same structure as items table';


-- -----------------------------------------------------
-- Table `wiki`.`events_has_instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wiki`.`events_has_instances` (
  `events_eid` INT UNSIGNED NOT NULL,
  `instances_iid` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`events_eid`, `instances_iid`),
  INDEX `fk_events_has_instances_instances1_idx` (`instances_iid` ASC) VISIBLE,
  INDEX `fk_events_has_instances_events1_idx` (`events_eid` ASC) VISIBLE,
  CONSTRAINT `fk_events_has_instances_events1`
    FOREIGN KEY (`events_eid`)
    REFERENCES `wiki`.`events` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_instances_instances1`
    FOREIGN KEY (`instances_iid`)
    REFERENCES `wiki`.`instances` (`iid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
